fn main() {
    println!("cargo:rerun-if-env-changed=TXN_INFO_CAP");

    let cap_0 = std::env::var_os("CARGO_FEATURE_TXN_INFO_CAP_0").is_some();
    let cap_64 = std::env::var_os("CARGO_FEATURE_TXN_INFO_CAP_64").is_some();
    let cap_128 = std::env::var_os("CARGO_FEATURE_TXN_INFO_CAP_128").is_some();
    let cap_192 = std::env::var_os("CARGO_FEATURE_TXN_INFO_CAP_192").is_some();
    let cap_custom = std::env::var_os("CARGO_FEATURE_TXN_INFO_CAP_CUSTOM").is_some();

    // Cargo unifies features across every crate that depends on this package within a single
    // build (e.g. `cargo build --workspace`, where this package is compiled both as a workspace
    // member using its own default features and as a dependency requesting a different tier), so
    // more than one `txn-info-cap-*` feature can end up enabled at once even though each
    // individual crate only asked for one. A larger capacity is a strict superset of a smaller
    // one, so we resolve that by taking the largest requested value instead of erroring.
    let mut candidates = Vec::new();
    if cap_0 {
        candidates.push(0);
    }
    if cap_64 {
        candidates.push(64);
    }
    if cap_128 {
        candidates.push(128);
    }
    if cap_192 {
        candidates.push(192);
    }
    if cap_custom {
        const DEFAULT_TXN_INFO_CAP: usize = 64;

        let parsed = std::env::var("TXN_INFO_CAP")
            .ok()
            .map(|raw| {
                raw.parse::<usize>().unwrap_or_else(|_| {
                    panic!(
                        "Invalid TXN_INFO_CAP='{}': expected a positive integer",
                        raw
                    )
                })
            })
            .unwrap_or(DEFAULT_TXN_INFO_CAP);

        if parsed == 0 {
            panic!("Invalid TXN_INFO_CAP=0: value must be greater than zero");
        }

        candidates.push(parsed);
    }

    let cap = candidates.into_iter().max().unwrap_or_else(|| {
        panic!(
            "No `txn-info-cap-*` feature is enabled; enable exactly one of \
             `txn-info-cap-0`, `txn-info-cap-64`, `txn-info-cap-128`, `txn-info-cap-192`, or \
             `txn-info-cap-custom`"
        );
    });

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR is set by cargo");
    let out_path = std::path::Path::new(&out_dir).join("txn_info_cap.rs");
    std::fs::write(
        &out_path,
        format!("// @generated by build.rs\npub const TXN_INFO_CAP: usize = {cap};\n"),
    )
    .unwrap_or_else(|e| panic!("failed to write generated file {}: {e}", out_path.display()));
}
