fn main() {
    println!("cargo:rerun-if-env-changed=TXN_INFO_CAP");

    const DEFAULT_TXN_INFO_CAP: usize = 64;

    let parsed = std::env::var("TXN_INFO_CAP")
        .ok()
        .map(|raw| {
            raw.parse::<usize>().unwrap_or_else(|_| {
                panic!(
                    "Invalid TXN_INFO_CAP='{}': expected a positive integer",
                    raw
                )
            })
        })
        .unwrap_or(DEFAULT_TXN_INFO_CAP);

    if parsed == 0 {
        panic!("Invalid TXN_INFO_CAP=0: value must be greater than zero");
    }

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR is set by cargo");
    let out_path = std::path::Path::new(&out_dir).join("txn_info_cap.rs");
    std::fs::write(
        &out_path,
        format!("// @generated by build.rs\npub const TXN_INFO_CAP: usize = {parsed};\n"),
    )
    .unwrap_or_else(|e| panic!("failed to write generated file {}: {e}", out_path.display()));
}
